services:


  php_frontrow:
    build: 
      context: .
      dockerfile: php.prod.dockerfile
    ports:
      - 9003:9000
    volumes:
      - ./src:/var/www/html
    
    networks:
      - frontrow_network
    
  
  composer:
    build: 
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - frontrow_network
 
  
  npm:
    image: node:18.20.3-alpine3.19
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
    networks:
      - frontrow_network

  artisan:
    build: 
      context: .
      dockerfile: php.prod.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - frontrow_network

    entrypoint: ["php", "/var/www/html/artisan"]

networks:
  frontrow_network:
    driver: bridge



  




    