name: FRONTROW TIKETS CI

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        working-directory: src
        run: composer install --no-interaction --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Node.js Dependencies
        working-directory: src
        run: npm install

      - name: Build Vite Assets
        working-directory: src
        run: npm run build
    # Add any additional steps or commands needed for your specific deployment setup
