name: FRONTROW TIKETS PR CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        working-directory: src
        run: composer install --no-interaction --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Switch to Node 18 (Nuxt 3.0.0 safe LTS)
          cache: "npm" # Cache node_modules

      - name: Install Node.js Dependencies
        working-directory: src
        run: npm ci --fetch-retries=5 --fetch-retry-maxtimeout=120000

      - name: Build Vite Assets
        working-directory: src
        run: npm run build
